name: holbegram
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_database: ^11.0.1
  image_picker: ^0.8.7+3
  uuid: ^3.0.6
  provider: ^6.0.3
  cached_network_image: ^3.2.0
  bottom_navy_bar: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/placeholder.png

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: InstagramSans
      fonts:
        - asset: assets/fonts/InstagramSans.ttf
